FROM debian:12-slim

RUN apt-get update && apt-get install -y curl bash ca-certificates && rm -rf /var/lib/apt/lists/*

RUN curl -sL "https://run.api7.ai/adc/install" | bash

ENV PATH="/root/.adc/bin:${PATH}"

WORKDIR /work

#ENTRYPOINT ["tail", "-f", "/dev/null"]